require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/vpns", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Vpn. As you add validations to Vpn, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.create(:vpn)
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Vpn.create! valid_attributes
      get vpns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      vpn = Vpn.create! valid_attributes
      get vpn_url(vpn)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_vpn_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      vpn = Vpn.create! valid_attributes
      get edit_vpn_url(vpn)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Vpn" do
        expect {
          post vpns_url, params: { vpn: valid_attributes }
        }.to change(Vpn, :count).by(1)
      end
      it "redirects to the created vpn" do
        post vpns_url, params: { vpn: valid_attributes }
        expect(response).to redirect_to(vpn_url(Vpn.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Vpn" do
        expect {
          post vpns_url, params: { vpn: invalid_attributes }
        }.to change(Vpn, :count).by(0)
      end
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post vpns_url, params: { vpn: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }
      it "updates the requested vpn" do
        vpn = Vpn.create! valid_attributes
        patch vpn_url(vpn), params: { vpn: new_attributes }
        vpn.reload
        skip("Add assertions for updated state")
      end
      it "redirects to the vpn" do
        vpn = Vpn.create! valid_attributes
        patch vpn_url(vpn), params: { vpn: new_attributes }
        vpn.reload
        expect(response).to redirect_to(vpn_url(vpn))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        vpn = Vpn.create! valid_attributes
        patch vpn_url(vpn), params: { vpn: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested vpn" do
      vpn = Vpn.create! valid_attributes
      expect { delete vpn_url(vpn) }.to change(Vpn, :count).by(-1)
    end
    it "redirects to the vpns list" do
      vpn = Vpn.create! valid_attributes
      delete vpn_url(vpn)
      expect(response).to redirect_to(vpns_url)
    end
  end
end
